project_id = "bxhnxfwrumeqvnpwymin"

[functions.rcon-command]
verify_jwt = true

[functions.server-status]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.process-payment]
verify_jwt = false